/*
  To run any code, you need to insert the namespace and class name after the dot in the StratupObject

  example: 
      StratupObject -- NAMESPACE.CLASSNAME -- StratupObject
*/
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>DataStructures.Graph.GraphApp</StartupObject>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
